title: Sukkari Dataset
description: A dataset for sorting Sukkari Dates
theme: just-the-docs

url: https://alialbeladi.github.io/dawan

aux_links:
  Template Repository: https://github.com/alialbeladi/dawan
